### ISSUE TITLE
Inconsistency regarding submission port / SMTPS port

### ISSUE THREAD

**Issue by aspettl** [johansmitsnl/docker-email-autodiscover#2]
Hi,

about a month ago I forked this repository because I wanted to advertise the submission port (SMTP with STARTTLS and authentication, port 587) instead of SMTP via SSL (port 465). Reason: port 587 is the standard, port 465 is not RFC compliant.
I did not yet create a pull request because I am not sure that my changes do really work, especially for Outlook. Furthermore, it was also needed to fork [gronke/email-autodiscover](https://github.com/gronke/email-autodiscover).

I see now that my changes have been incorporated partially into this repository (https://github.com/johansmitsnl/docker-email-autodiscover/commit/7476c07f9e625ecd53b1f2bb8df3fc7e827516ba and https://github.com/johansmitsnl/docker-email-autodiscover/commit/ed2e06a60d68ababe1522295d86919f95e76f4cf). This means SMTP_PORT has the default 587 instead of 465, and SMTP_SOCKET/IMAP_SOCKET exist but do not have any impact, which is a bit confusing for users. So we should probably adjust the default and remove these two variables (or support them ;-)).

**Comment by johansmitsnl** [comment]
You are right, missed the change on this.
Added the change and it is not in development. Feel free to submit a PR.

I added the change, could you submit a PR to the submodule owner for you change?
https://github.com/johansmitsnl/docker-email-autodiscover/commit/d3ef2205b661623e6f610c5c87de1c31a0ed9668
